### ISSUE TITLE
Fitting stops soon after 99999 spectra

### ISSUE THREAD

**Issue by weiaip** [rwesson/ALFA#11]
I am currently trying to fit a 2D dataset with 243891 rows and discovered that ALFA stops soon after reaching 100000 spectra, with this message:

```
            (thread 35) : skipped row  *****
            (thread 35) : skipped row  *****
            (thread 35) : skipped row  *****
            (thread 35) : skipped row  *****
            (thread 35) : skipped row  *****
At line 225 of file spectralfit.f90 (unit = 103, file = '')
Fortran runtime error: File already opened in another unit
            (thread 35) : skipped row  *****
            (thread 35) : skipped row  *****
```

This is with version v1.0-9-g2fc12c1. This fix should simply be to write filenames with morethan 5 digits if the dataset is larger than 99999 spectra.

**Comment by rwesson** [comment]
I had not anticipated people fitting files that large!  I have now fixed the code so that file names have enough digits to properly write out all the fitted spectra.

eb6bafca0fa2aa58c68ac9773d6259db19135a9f
