### ISSUE TITLE
Adding to existing optical linelists: new additions not being measured even when present in input spectrum

### ISSUE THREAD

**Issue by catherine-manea** [rwesson/ALFA#28]
Hi again!  Sorry to keep bugging you.  I was wondering if I could ask you about adding lines to the existing optical linelists?  I've been trying to add a few lines to optical_deep, optical_strong, etc., but whenever I run ALFA, those lines never seem to be detected even when they exist rather strongly in my input spectra.  I was wondering if you might have any advice for adding lines and ensuring ALFA looks for them while measuring?  Here is an example of a line I'd love to add: [Xe IV] 7535.03.  When adding it to an optical linelist, I simply open the linelist file in a text editor and add it as so:

(from optical_ultradeep.cat)
...
7519.50 & C II       & V16.08     & 2p3 2P*    & 3p' 2P     &          4 &        4\\
7519.86 & C II       & V16.08     & 2p3 2P*    & 3p' 2P     &          2 &        2\\
7530.83 & [Cl IV]    & F1         & 3p2 3P     & 3p2 1D     &          3 &        5\\
**7535.03 & [Xe IV]    &            &                &                  &            &            \\**
7551.00 & N II       &            & 3P         & 3P*        &          5 &        3\\
7579.41 & Fe II      &            & y4G*       & 4s2 2H     &          8 &       10\\
7592.75 & He II      & 5.10       & 5g+ 2G     & 10h+ 2H*   &         50 &         \\
...

And then I save it and run ALFA.  I'm guessing I might be missing a step, like the hint you provided me last time with running `make new && sudo make install` again?  I really love ALFA's ability to deblend lines and would love to use it to measure these lines not in the linelist.  Thanks so much for your help.

**Comment by rwesson** [comment]
Hi again! Must be that ALFA is still reading in the default line lists. If you did `sudo make install`, then the line list files will have been copied to system directories, and ALFA looks for them there. You can see which files it is reading in in the terminal output. On my system, for example, the terminal output includes

``              strong line catalogue:            /usr/share/alfa/optical_strong.cat``
``              deep line catalogue:              /usr/share/alfa/optical_deep.cat``

If you edited the files in the source directory, then `sudo make install` would copy the updated files to the system directories. Or, maybe easier, you can specify the files you edited on the command line with the `--deep-catalogue` option.

Hope that sorts it!

**Comment by catherine-manea** [comment]
Thank you so much for your help, again.  Looks like `sudo make install` worked out.  I'm looking forward to measuring these additional lines with ALFA!
